#!/bin/sh
sed -i "s/${CONTAINER_USER}:\([^:]*\)\(:[^:]\+\)\{2\}/${CONTAINER_USER}:\1:${CONTAINER_UID}:${CONTAINER_GID}/" /etc/passwd
sed -i "s/${CONTAINER_GROUP}:.*/${CONTAINER_GROUP}:x:${CONTAINER_GID}:/" /etc/group